spring:
  application:
    name: desafio-picpay
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    baseline-on-migrate: true
    user: sa
    password:
    enabled: true

picpay:
  authorization-url: https://util.devi.tools/api/v2/authorize
  notification-url: https://util.devi.tools/api/v1/authorize # Same url, for test purpose
