CREATE TABLE IF NOT EXISTS TRANSACTIONS (
                                            ID VARCHAR(255) NOT NULL,
    DATE TIMESTAMP DEFAULT NULL,
    PAYEE_ID BIGINT DEFAULT NULL,
    PAYER_ID BIGINT DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PAYEE_ID) REFERENCES WALLETS(ID),
    FOREIGN KEY (PAYER_ID) REFERENCES WALLETS(ID)
);